version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_PASSWORD=abc
      - MYSQL_USER=abc
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - DB_CONN=abc:abc@tcp(db:3306)/api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
